[package]
name = "rms-check-lsp"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
license = "GPL-3.0"
description = "Language server for Age of Empires random map scripts."
repository = "https://github.com/goto-bus-stop/rms-check.git"
edition = "2018"

[dependencies]
codespan = "^0.4.0"
codespan-lsp = "^0.3.0"
jsonrpc-core = "^13.0.0"
languageserver-types = "^0.54.0"
rms-check = { path = "../rms-check/" }
serde_json = "^1.0.37"
