<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- from https://github.com/mangudai/vscode -->
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>AoE2 Random Map Script</string>
    <key>scopeName</key>
    <string>source.aoe2-rms</string>
    <key>fileTypes</key>
    <array>
      <string>rms</string>
    </array>
    <key>uuid</key>
    <string>0b2a431f-f33a-4fdb-97db-f9974ad80a0a</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#multilineComment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#sectionHeader</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#conditional</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#random</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#command</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#directive</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>multilineComment</key>
      <dict>
        <key>name</key>
        <string>comment.block.aoe2-rms</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <key>sectionHeader</key>
      <dict>
        <key>name</key>
        <string>storage.type.section.aoe2-rms</string>
        <key>match</key>
        <string>\&lt;[A-Z_]+\&gt;</string>
      </dict>
      <key>conditional</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#conditionalStart</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#conditionalEnd</string>
          </dict>
        </array>
      </dict>
      <key>random</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#randomStart</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#randomEnd</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#randomChance</string>
          </dict>
        </array>
      </dict>
      <key>command</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#commandStatement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#commandBlock</string>
          </dict>
        </array>
      </dict>
      <key>directive</key>
      <dict>
        <key>name</key>
        <string>meta.directive.aoe2-rms</string>
        <key>begin</key>
        <string>\#(const|define|include_drs)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.other.directive.aoe2-rms</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\n|/\*)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>conditionalStart</key>
      <dict>
        <key>name</key>
        <string>meta.conditional.aoe2-rms</string>
        <key>match</key>
        <string>(if|elseif|else)(\s+(\b[^\s!@#\$%\^&amp;\*\(\)\-\+=;:'"&lt;&gt;{}\[\]\?\/\\][^\s;'"&lt;&gt;{}\[\]\/\\]*\b))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.aoe2-rms</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.const.aoe2-rms</string>
          </dict>
        </dict>
      </dict>
      <key>conditionalEnd</key>
      <dict>
        <key>name</key>
        <string>keyword.control.conditional.aoe2-rms</string>
        <key>match</key>
        <string>endif</string>
      </dict>
      <key>randomStart</key>
      <dict>
        <key>name</key>
        <string>keyword.control.random.aoe2-rms</string>
        <key>match</key>
        <string>\bstart_random\b</string>
      </dict>
      <key>randomEnd</key>
      <dict>
        <key>name</key>
        <string>keyword.control.random.aoe2-rms</string>
        <key>match</key>
        <string>\bend_random\b</string>
      </dict>
      <key>randomChance</key>
      <dict>
        <key>name</key>
        <string>meta.random.chance.aoe2-rms</string>
        <key>match</key>
        <string>\b(percent_chance)\s+(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.random.aoe2-rms</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.aoe2-rms</string>
          </dict>
        </dict>
      </dict>
      <key>commandStatement</key>
      <dict>
        <key>name</key>
        <string>meta.command.aoe2-rms</string>
        <key>begin</key>
        <string>\b[a-z_]+</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.aoe2-rms</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\n|/\*|\{)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>commandBlock</key>
      <dict>
        <key>name</key>
        <string>meta.commandBlock.aoe2-rms</string>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.mapping.begin.aoe2-rms</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.mapping.end.aoe2-rms</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#conditional</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#random</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#multilineComment</string>
          </dict>
        </array>
      </dict>
      <key>attribute</key>
      <dict>
        <key>name</key>
        <string>variable.parameter.attribute.aoe2-rms</string>
        <key>match</key>
        <string>\b[a-z_]+</string>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>variable.other.const.aoe2-rms</string>
        <key>match</key>
        <string>\b[^\s!@#\$%\^&amp;\*\(\)\-\+=;:'"&lt;&gt;{}\[\]\?\/\\][^\s;'"&lt;&gt;{}\[\]\/\\]*\b</string>
      </dict>
      <key>number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.aoe2-rms</string>
        <key>match</key>
        <string>(\B\-|\b)\d+\b</string>
      </dict>
    </dict>
  </dict>
</plist>
